import pytest
from bs4 import BeautifulSoup
from xpert.scraper import _parse_tweet

# High-Fidelity Real-World Simulation Fixtures (Aligned with scraper.py)

REAL_WORLD_EVERYTHING_TWEET = """
<div class="timeline-item">
    <div class="tweet-body">
        <div class="tweet-header">
            <a class="username" title="Elon Musk">@elonmusk</a>
            <span class="fullname">Elon Musk</span>
            <span class="tweet-header-items">
                <span class="icon-pencil" title="Edited at 9:42 PM · Mar 24, 2026"></span>
            </span>
        </div>
        <div class="tweet-content media-body" dir="auto">The future is looking bright! 🚀</div>
        <div class="attachments">
            <div class="gallery-row">
                <div class="attachment image">
                    <a class="still-image" href="/elonmusk/status/12345/photo/1">
                        <img src="https://nitter.net/pic/media%2Fimg1.jpg" alt="A sleek futuristic rocket landing on Mars." />
                    </a>
                </div>
                <div class="attachment image">
                    <a class="still-image" href="/elonmusk/status/12345/photo/2">
                        <img src="https://nitter.net/pic/media%2Fimg2.jpg" alt="A sustainable city on the red planet." />
                    </a>
                </div>
            </div>
        </div>
        <div class="community-note">
            <div class="community-note-text">
                Readers added context they thought people might want to know.<br><br>
                This image was generated by AI and does not represent a real landing. Landing on Mars is still in development.
            </div>
        </div>
        <div class="tweet-stats">
            <span class="tweet-stat"><span class="icon-comment"></span> 15.4K</span>
            <span class="tweet-stat"><span class="icon-retweet"></span> 42.1K</span>
            <span class="tweet-stat"><span class="icon-heart"></span> 250K</span>
        </div>
    </div>
</div>
"""

REAL_WORLD_QUOTE_TWEET = """
<div class="timeline-item">
    <div class="tweet-body">
        <div class="tweet-header">
            <a class="username">@tech_insider</a>
        </div>
        <div class="tweet-content">Check out this amazing news!</div>
        <div class="quote">
            <a class="quote-link" href="/nasa/status/98765"></a>
            <div class="quote-head">
                <a class="username">@nasa</a>
                <span class="fullname">NASA</span>
                <span class="quote-time">Mar 25</span>
            </div>
            <div class="quote-text">We are returning to the moon.</div>
        </div>
    </div>
</div>
"""

def test_everything_tweet_simulation():
    """Verify a complex 'Everything' tweet with edited status, multiple images, and community notes."""
    soup = BeautifulSoup(REAL_WORLD_EVERYTHING_TWEET, "lxml")
    body = soup.select_one(".tweet-body")
    result = _parse_tweet(body)
    
    # 1. Author and Content
    assert result["author"] == "elonmusk"
    assert "future is looking bright" in result["text"]
    
    # 2. Edited Status
    assert result["is_edited"] is True
    
    # 3. Community Notes (Multi-paragraph)
    assert result["has_community_note"] is True
    assert "Readers added context" in result["community_note"]
    assert "Landing on Mars is still in development" in result["community_note"]
    
    # 4. Multiple Images with Alt Text
    assert len(result["images"]) == 2
    assert result["images"][0]["alt"] == "A sleek futuristic rocket landing on Mars."
    assert result["images"][1]["alt"] == "A sustainable city on the red planet."
    
    # 5. Stats (Verification of icons using span)
    assert result["likes"] == 250000
    assert result["retweets"] == 42100

def test_quote_tweet_simulation():
    """Verify basic quote tweet parsing in a real-world structure."""
    soup = BeautifulSoup(REAL_WORLD_QUOTE_TWEET, "lxml")
    body = soup.select_one(".tweet-body")
    result = _parse_tweet(body)
    
    assert result["author"] == "tech_insider"
    assert result["quote_tweet"] is not None
    assert result["quote_tweet"]["author"] == "nasa"
    assert result["quote_tweet"]["id"] == "98765"
    assert "returning to the moon" in result["quote_tweet"]["text"]

def test_malformed_community_note_simulation():
    """Verify robustness when community note is present but empty or strangely formatted."""
    html = '<div class="tweet-body"><div class="community-note"></div></div>'
    soup = BeautifulSoup(html, "lxml")
    body = soup.select_one(".tweet-body")
    result = _parse_tweet(body)
    
    assert result["has_community_note"] is True
    assert result["community_note"] == ""
